package com.uet.hocvv.equiz.common;

public enum CommonMessage {
	USERNAME_IS_REQUIRED,
	USERNAME_EXISTED,
	USER_NOT_FOUND,
	VERIFY_LINK_HAS_EXPRIED,
	SUCCESS,
	FAIL,
	NOT_FOUND,
	EXISTED,
	WRONG_PASSWORD_TO_JOIN,
	ALREADY_JOINED_THIS_CLASSROOM
}
